### ISSUE TITLE
Current Situation

### ISSUE THREAD

**Issue by hqt** [hqt/street-router#3]
Ngoan will works this topic. We will post detail here for people easier to follow.

**Comment by ngoantt** [comment]
@hqt vào check thử nội dung vậy đã được chưa ?

**Comment by hqt** [comment]
mày có google translate không mà câu văn bựa vậy @_@ Với lại sai chính tả nhiều. bật spelling và checker lên đi.
Với lại Advantages và DisAdvantages là của Nam làm nha. Mài làm tiếp Problem Definition. Có sẵn task trên này nè. :">

**Comment by ngoantt** [comment]
có translate và có cả chỉnh sửa..thấy cũng ổn mà..
